### ISSUE TITLE
npm 프로젝트를 만들어요

### ISSUE THREAD

**Issue by jb-** [saeromCho/shumblr#1]
우리는 JavaScript 프로젝트를 진행할 것이고, 프로젝트 관리를 위해 npm을 사용할 것입니다.
shumblr 라는 이름의 npm 프로젝트를 만듭니다.

**Comment by jb-** [comment]
모든 걸 전부 세팅하는 것이 아닙니다. 앞으로 계속 필요에 따라 npm 패키지들은 추가될 거예요.
가장 기본적인 형태의 package.json 및 package-lock.json 을 생성해서 커밋해주시면 됩니다.

**Comment by jb-** [comment]
https://www.youtube.com/watch?v=pa4dc480Apo 
저는 제일 처음에 이 영상으로 npm에 입문했습니다.

https://docs.npmjs.com/getting-started/what-is-npm
그리고 이 공식 가이드도 참고해주세요

**Comment by saeromCho** [comment]
제가 한 번 시도해 볼까요? ㅎ..ㅎ(자신 없지만 해볼까요..? 자신감을 길러라 롬아 제발)

**Comment by jb-** [comment]
네 처음에 진입 장벽이 좀 있지만, 공부를 좀 하고 나면, 매우 간단한 일입니다.

**Comment by saeromCho** [comment]
네 알겠습니다, 그래서 오늘 Agile 30Minutes는 무엇인가요?

**Comment by jb-** [comment]
그냥 이 일을 삼십분동안 하시고, 그 결과를 공유해 주시면 됩니다. 공부를 하셨든, 코드를 커밋하셨든, 무엇이든지요.

**Comment by saeromCho** [comment]
넵 알겠습니다~!!!

**Comment by saeromCho** [comment]
https://scotch.io/bar-talk/how-to-build-and-publish-a-npm-package

이 링크를 통해서 shumblr packge.json파일을 생성했습니다.
내용은 drfts의 lib-tz의 packge.json파일을 참고해서 넣었구요.
제가 오늘 다룬 내용이 종빈님이 생각하시기엔 너무 쉬운 내용이라는 생각이 드는데, 이해하면서 하느라 시간이 좀 걸렸어용.
근데 이게 종빈님이 의도하신 부분이 맞는 건지는 아직 모르겠습니다ㅠ.ㅠ
(아니라면 말씀해주세요, 재도전 할거에요!)
* 초반이라 좀 오래걸리는 건 사실이에요, 그럼에도 저한테 다 도움이 될 게 분명하게 맞기 때문에 전 좋습니다 :)

**Comment by jb-** [comment]
세상에 쉬운 것은 없지요. 처음엔 다 어렵습니다. 
1. `package-lock.json` 파일도 커밋해주셔야 합니다. 
2. `/src/index.js` 는 왜 만드신 건가요?
3. 혹시 `package.json` 파일을 직접 수정하셨나요? 만약 그러셨다면, 파일에 직접 추가하신 내용은 뭐고, 그걸 왜 하셨는지 궁금합니다.

**Comment by saeromCho** [comment]
1. package-lock.json 파일, 생성해서 커밋 푸쉬 했습니다.
2. 아 index.js는 해당 링크를 따라하다가 한 번 만들어 보았습니다.
3. 네 수정했습니답, 주신 커멘트대로 해당 이슈 커멘트 달겠습니다!!!

**Comment by saeromCho** [comment]
name - "shumblr" => 우리 shumblr 이름.
description - "This is your Terminal Shell + 'Tumblr'" =>  우리 shumblr 소개말.
main - index.js => 링크를 보고 만들고 나니까, 메인 필드라는 게 있더라구요. 그래서 메인 필드가 index.js인 거 같아서 적었습니다.
repository - "type" : git, "url" : "우리 깃 주소"  => 이건 종빈님이 작성하신 lib-tz의 package.json 파일을 참고해서 따라 적었습니다.
bugs - "url" : "우리 깃의 issues링크" => 이 또한 lib-tz의 package.json 파일을 참고해서 적었습니다.
homepage - "우리 깃의 readme 주소" => 이 또한 마찬가지 입니다.
dependecies => 이 또한 참고. 사용하게 될 기술스펙의 디펜던시를 위해 적어두었고, 아직 정한 게 없어서 빈 걸로 남겨두었습니다.
devDependencies => 이 또한 참고인데, 위의 디펜던시와의 차이점은 잘 몰라 공부한 뒤, 코멘트로 달도록 하겠습니다.

**Comment by saeromCho** [comment]
위키에 내용 첨부하겠습니다 :)

**Comment by jb-** [comment]
`package-lock.json` 은 어떻게 만드셨나요

**Comment by saeromCho** [comment]
우리 shumblr 디렉토리 내에서 , npm init 으로 package.json 디폴트 파일을 만들었구요. 
이후 package.json파일 내용을 수정을 한 뒤, 
shumblr 디렉토리 내에서 npm istall을 하여 package-lock.json을 만들었습니다.

**Comment by jb-** [comment]
맞아요 사실 제가 원했던 답은
`$ npm init -y`
`$ npm install` 
이 두개 한담에 그냥 커밋하는 거였어요.
npm 관해서는 쓰다 보시면 더 감이 오실 거예요

**Comment by saeromCho** [comment]
지금 보면 진짜 간단한 거 였네욬ㅋㅋㅋㅋ 덕분에 공부했습니당!!!
